name = "feedback-analyzer"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "feedback-db-v11"
database_id = "d0e2731e-194c-4ee7-9ca5-e57fc2e4d51a"

[ai]
binding = "AI"
